services:
  - type: worker
    name: curio-discord-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: CHANNEL_NAME
        value: curio-index
